# Generated by Django 5.2.8 on 2026-05-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('chest_pain_type', models.CharField(max_length=10)),
                ('resting_bp', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('fasting_bs', models.IntegerField()),
                ('resting_ecg', models.CharField(max_length=10)),
                ('max_hr', models.IntegerField()),
                ('exercise_angina', models.CharField(max_length=1)),
                ('oldpeak', models.FloatField()),
                ('st_slope', models.CharField(max_length=10)),
                ('prediction', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
